export const SET_BALANCE_PENDING = 'SET_BALANCE_PENDING'
export const SET_BALANCE = 'SET_BALANCE'

export const SET_ACCOUNTS_PENDING = 'SET_ACCOUNTS_PENDING'
export const SET_ACCOUNTS = 'SET_ACCOUNTS'
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT'

export const SET_TRANSACTIONS_PENDING = 'SET_TRANSACTIONS_PENDING'
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS'
